version: "3.8"

services:
  postgres:
    image: postgres:12.8-alpine
    command: bash -c "psql gamecms -f /sql/schema.sql && psql gamecms -f /sql/tables_insert.sql"
    working_dir: /sql
    volumes:
      - gamecms-data:/var/lib/postgresql/data
      - ./sql:/sql
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: root
      POSTGRES_DB: gamecms

volumes:
  gamecms-data: