version: "3.8"

services:
  app:
    image: python:3.9.5
    command: sh -c "cd /app && pip install -r requirements.txt && gunicorn -b 0.0.0.0:5000 app:app"
    ports:
      - 5000:5000
    working_dir: /app
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    environment:
      FLASK_APP: app
      FLASK_ENV: production
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: root
      POSTGRES_DB: gamecms
  postgres:
    image: postgres:12.8-alpine
    volumes:
      - gamecms-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: root
      POSTGRES_DB: gamecms

volumes:
  gamecms-data: